[project]
name = "reversed-proxy-service"
version = "0.1.0"
description = "Reversed proxy"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "requests>=2.32.5",
]

